### ISSUE TITLE
Where is the code?

### ISSUE THREAD

**Issue by athoune** [bleemeo/bleemeo-agent#1]

**Comment by lporcheron** [comment]
Hi Mathieu,
The code is still on our internal git repository. But it should be pushed shortly. We let you know when it's pushed.

**Comment by athoune** [comment]
release early, release often?

**Comment by lporcheron** [comment]
Yes, but that's not related to the git repository location :)

**Comment by athoune** [comment]
How can I choose bleemeo without knowing the agent quality? unmaintened ruby agent for ruby bites me hard.

Mqtt is a great choice, but just one buzzword to describe a tool?

Come on, I need to support french tech! La french tech de Toulouse, en plus !

**Comment by lporcheron** [comment]
Bleemeo agent code is now available :)
