### ISSUE TITLE
Feature request: all conf options available as ENV VARS

### ISSUE THREAD

**Issue by krezreb** [bleemeo/bleemeo-agent#6]
I would like to be able to use the machine's hostname for the bleemeo.initial_agent_name
I am deploying to a large number of machines and am scripting the whole process.
I have followed this documentation regarding the agent config: https://docs.bleemeo.com/agent/configuration/

I noticed that many of the other options can be set as environment variables.  So I assumed that I could set BLEEMEO_AGENT_BLEEMEO_INITIAL_AGENT_NAME but that did not work.

In short I would like my agent deploy script to look like this:

```
wget -O /tmp/bleemeo.sh "https://get.bleemeo.com?accountId=$ACCOUNT_ID&registrationKey=$KEY"
export BLEEMEO_AGENT_BLEEMEO_INITIAL_AGENT_NAME=$(hostname)
bash /tmp/bleemeo.sh
```

This would have the major advantage of not having to create a conf file in /etc/bleemeo/agent.conf.d and use templating to put the hostname in bleemeo.initial_agent_name.

Would it be possible to have all config options be overwriteable via ENV VARS?

**Comment by PierreF** [comment]
Hello,

actually, all configurations could be overridden by environment variable when starting the agent... but the installer script does not use them. The override through environment variables are mostly useful when Bleemeo agent is run inside a container.

The main issue is that environment variable by itself won't be transmitted further that installation script (apt and/or systemd will drop them when running the agent, which is the one using the settings). Also environment variable won't be kept across reboot.

The only solution I could think of would be for the installation script to write a file in agent.conf.d with the content of those environment variable, but then we are back to "create a conf file and use templating" problem.

I fear that having the installation script handle this will make it too complex. Having a short script which is easy to audit is something valuable.

For your use-case, couldn't you do something like ?
```
wget -O /tmp/bleemeo.sh "https://get.bleemeo.com?accountId=$ACCOUNT_ID&registrationKey=$KEY"
mkdir -p /etc/bleemeo/agent.conf.d/
echo "bleemeo: {initial_agent_name: '$(hostname)'}" > /etc/bleemeo/agent.conf.d/30-initial-name.conf
bash /tmp/bleemeo.sh
```

**Comment by krezreb** [comment]
Thanks for your feedback.  Indeed I am using this natively via systemd, so now I see that ENV VARS won't really work.

I ended up following the native debian instructions here https://docs.bleemeo.com/agent/install-debian-ubuntu-package/

So I did have to do a little of templating but it works
